server:
  port: 8093

spring:
#  profiles:
#    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_boot
    #url: jdbc:mysql://175.178.185.38:3306/db_boot
    username: root
    #password: root123
    password: itcast
    name: db_boot
#  redis:
    #    password: itcast
#    host: localhost
#    port: 6379

mybatis:
  mapper-locations: classpath:/com/epoch/mapper/*.xml
  type-aliases-package: com.epoch.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
