server:
  port: 8093

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 线上数据库连接地址
#    url: jdbc:mysql://175.178.185.38:43306/db_boot
    #本地测试地址
    url: jdbc:mysql://localhost:43306/db_boot
    username: "root"
    #本地数据库密码
    #password: itcast
    #线上数据库密码
    password: "520584"
    name: db_boot
    #redis:
    #password: itcast
    #host: localhost
    #port: 6379

mybatis:
  mapper-locations: classpath:/com/epoch/mapper/*.xml
  type-aliases-package: com.epoch.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
